### ISSUE TITLE
DobExplorer and Sate should be installed with runtime part of Core

### ISSUE THREAD

**Issue by fumpa** [SafirSDK/safir-sdk-core#285]
DobExplorer and Sate are today installed in the developer part of the installation of Core
Both should be moved to the runtime part of the installation.

**Comment by DonOregano** [comment]
I'm not sure I like the idea, honestly.
The purpose of the "Runtime" part of the installation package is to provide exactly only those things that are needed to run a Safir SDK Core based system. Installing Sate and Dobexplorer on deployed systems is not a great idea, since they can provide access to parts of the system only meant for developers.
But then I can understand your reasoning, it is a pain not to have those tools accessible in a test environment...
Maybe a better solution is to add another installation component "Tools", that contains Sate, Dobexplorer, backdoor etc?

**Comment by fumpa** [comment]
As long as we can install the tools from the command line I see no problem to have a "Tools" installation.
Which tools that should be a part of Tools and which tools that should come with the "Developer" installation is another question that I can't answer now.

**Comment by DonOregano** [comment]
I'm going to add the Backdoor command sender "bd" to the Tools component as well.
