### ISSUE TITLE
Control and Data adress binds to local host instead of  parameters set in ThisNodeParameters

### ISSUE THREAD

**Issue by stfeky** [SafirSDK/safir-sdk-core#289]
Control and Data address binds to local host (127.0.0.1) instead of  parameters set in ThisNodeParameters.
This only happens on computers that run the dob as service.

the consequence is that no communication is possible with other nodes

**Comment by DonOregano** [comment]
Cannot reproduce. Have tried using SrvStart.exe from http://rozanski.org.uk/software, but everything works perfectly.

After communication with reporter it appears that the real bug is about the service starting before the desired network interface has appeared. Opened a new bug for that issue; #293.
